/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  SubdomainRegistrations as SubdomainRegistrations
} from './components/subdomain-registrations/subdomain-registrations';

declare global {
  interface HTMLSubdomainRegistrationsElement extends SubdomainRegistrations, HTMLElement {
  }
  var HTMLSubdomainRegistrationsElement: {
    prototype: HTMLSubdomainRegistrationsElement;
    new (): HTMLSubdomainRegistrationsElement;
  };
  interface HTMLElementTagNameMap {
    "subdomain-registrations": HTMLSubdomainRegistrationsElement;
  }
  interface ElementTagNameMap {
    "subdomain-registrations": HTMLSubdomainRegistrationsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "subdomain-registrations": JSXElements.SubdomainRegistrationsAttributes;
    }
  }
  namespace JSXElements {
    export interface SubdomainRegistrationsAttributes extends HTMLAttributes {
      registrations?: any[];
    }
  }
}


import {
  SubdomainRegistryApp as SubdomainRegistryApp
} from './components/subdomain-registry-app/subdomain-registry-app';

declare global {
  interface HTMLSubdomainRegistryAppElement extends SubdomainRegistryApp, HTMLElement {
  }
  var HTMLSubdomainRegistryAppElement: {
    prototype: HTMLSubdomainRegistryAppElement;
    new (): HTMLSubdomainRegistryAppElement;
  };
  interface HTMLElementTagNameMap {
    "subdomain-registry-app": HTMLSubdomainRegistryAppElement;
  }
  interface ElementTagNameMap {
    "subdomain-registry-app": HTMLSubdomainRegistryAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "subdomain-registry-app": JSXElements.SubdomainRegistryAppAttributes;
    }
  }
  namespace JSXElements {
    export interface SubdomainRegistryAppAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  SubdomainRegistryForm as SubdomainRegistryForm
} from './components/subdomain-registry-form/subdomain-registry-form';

declare global {
  interface HTMLSubdomainRegistryFormElement extends SubdomainRegistryForm, HTMLElement {
  }
  var HTMLSubdomainRegistryFormElement: {
    prototype: HTMLSubdomainRegistryFormElement;
    new (): HTMLSubdomainRegistryFormElement;
  };
  interface HTMLElementTagNameMap {
    "subdomain-registry-form": HTMLSubdomainRegistryFormElement;
  }
  interface ElementTagNameMap {
    "subdomain-registry-form": HTMLSubdomainRegistryFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "subdomain-registry-form": JSXElements.SubdomainRegistryFormAttributes;
    }
  }
  namespace JSXElements {
    export interface SubdomainRegistryFormAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  SubdomainRenewForm as SubdomainRenewForm
} from './components/subdomain-renew-form/subdomain-renew-form';

declare global {
  interface HTMLSubdomainRenewFormElement extends SubdomainRenewForm, HTMLElement {
  }
  var HTMLSubdomainRenewFormElement: {
    prototype: HTMLSubdomainRenewFormElement;
    new (): HTMLSubdomainRenewFormElement;
  };
  interface HTMLElementTagNameMap {
    "subdomain-renew-form": HTMLSubdomainRenewFormElement;
  }
  interface ElementTagNameMap {
    "subdomain-renew-form": HTMLSubdomainRenewFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "subdomain-renew-form": JSXElements.SubdomainRenewFormAttributes;
    }
  }
  namespace JSXElements {
    export interface SubdomainRenewFormAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  SubdomainUpdateForm as SubdomainUpdateForm
} from './components/subdomain-update-form/subdomain-update-form';

declare global {
  interface HTMLSubdomainUpdateFormElement extends SubdomainUpdateForm, HTMLElement {
  }
  var HTMLSubdomainUpdateFormElement: {
    prototype: HTMLSubdomainUpdateFormElement;
    new (): HTMLSubdomainUpdateFormElement;
  };
  interface HTMLElementTagNameMap {
    "subdomain-update-form": HTMLSubdomainUpdateFormElement;
  }
  interface ElementTagNameMap {
    "subdomain-update-form": HTMLSubdomainUpdateFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "subdomain-update-form": JSXElements.SubdomainUpdateFormAttributes;
    }
  }
  namespace JSXElements {
    export interface SubdomainUpdateFormAttributes extends HTMLAttributes {
      
    }
  }
}

